### ISSUE TITLE
map file does not exists

### ISSUE THREAD

**Issue by unlight** [PatrikLythell/sigh-postcss#2]
``` css
:fullscreen a {
    display: flex;
}
/*# sourceMappingURL=style.css.map */
```

Result file saved ok, but..
But `style.css.map` doesn't exists.
